export const en_snake_case = {
    continue: "Continue",
    wallet: "Wallet",
    home: "Home",
    earnings: "Earnings",
    profile: "Profile",
    faq1: "How do I place an order?",
    faq1_description: "To place an order, simply browse through our menu, select the items you'd like to order, and proceed to checkout. You can choose your preferred payment method and delivery address before confirming your order.",
    faq2: "What are the delivery charges?",
    faq2_description: "Delivery charges vary depending on your location and the restaurant you're ordering from. You can view the delivery charges applicable to your order before finalizing it during the checkout process.",
    faq3: "Can I track my order?",
    faq3_description: "Yes, you can track your order in real-time from the moment it's confirmed to when it's out for delivery. You'll receive updates on the status of your order through notifications on the app.",
    faq4: "How long does delivery take?",
    faq4_description: "Delivery times may vary depending on factors such as the restaurant's preparation time, traffic conditions, and your location. However, we strive to deliver your order within a reasonable timeframe, typically ranging from 30 to 60 minutes.",
    faq5: "Can I cancel my order after it's been placed?",
    faq5_description: "Yes you can cancel your order once it is placed. However, once the order has been prepared and sent out for delivery, you can no longer cancel the order. You may contact the restaurant directly for assistance.",
    faq6: "How can I provide feedback on my experience?",
    faq6_description: "You can provide feedback through the app by rating your order and leaving comments. You can also give a rating to the restaurant and leave a review.",
    faq7: "Can I order from multiple places at the same time?",
    faq7_description: "Unfortunately, you can't choose from multiple restaurants within the same order. However, you can place separate orders from different restaurants at the same time.",
    earnings_summary: "Earnings Summary",
    deliveries: "Deliveries",
    total_earnings: "Total Earnings",
    order_history: "Order History",
    view_details: "View Details",
    order_no: "Order No",
    order_date: "Order Date",
    earnings_order_details: "Earnings Order Details",
    order_placed_successfully: "Order placed successfully",
    order_cancelled_successfully: "Order cancelled successfully",
    error_while_placing_order: "Error while placing order",
    error_while_cancelling_order: "Error while cancelling order",
    please_enter_your_name: "Please enter your name",
    please_enter_your_email: "Please enter your email",
    please_enter_your_password: "Please enter your password",
    invalid_email_address: "Invalid email address",
    password_must_be_at_least_8_characters_long: "Password must be at least 8 characters long",
    passwords_do_not_match: "Passwords do not match",
    please_select_your_preferred_payment_method: "Please select your preferred payment method",
    please_select_your_delivery_address: "Please select your delivery address",
    please_enter_your_order_details: "Please enter your order details",
    please_select_your_preferred_delivery_time: "Please select your preferred delivery time",
    please_provide_your_feedback: "Please provide your feedback",
    thank_you_for_your_feedback: "Thank you for your feedback",
    this_screen_does_not_exist: "This screen does not exist.",
    go_to_home_screen: "Go to home screen!",
    logout_failed: "Logout failed",
    order_number: "Order number:",
    clear_filters: "Clear Filters",
    please_wait: "Please wait...",
    apply_filter: "Apply Filter",
    summary: "Summary",
    total_tips: "Total Tips",
    total_deliveries: "Total Deliveries",
    order_id: "Order ID #",
    payment: "Payment",
    completed: "Completed",
    no_record_found: "No record found.",
    failed_to_update_bank_details: "Failed to update bank details",
    account_name_is_required: "Account Name is required",
    account_number_is_required: "Account Number is required",
    routing_number_is_required: "Routing Number is required",
    bank_name_is_required: "Bank Name is required",
    account_code_is_required: "Account Code is required",
    your_bank_details_have_been_updated_successfully: "Your bank details have been updated successfully.",
    bank_details_updated: "Bank Details Updated",
    bank_name: "Bank Name",
    swiss_bank: "Swiss Bank",
    account_number: "Account Number",
    routing_number: "Routing Number",
    account_name: "Account Name",
    account_code: "Account Code",
    bank_account: "Bank Account",
    iban_swift_bsb: "IBAN / Swift / BSB",
    iban_placeholder: "Enter IBAN/Swift/BSB code",
    account_name_placeholder: "Enter account holder name",
    confirm: "Confirm",
    availability: "Availability",
    available: "Available",
    not_available: "Not Available",
    please_enter_a_valid_email_address: "Please enter a valid email address",
    please_enter_a_valid_password: "Please enter a valid password",
    whats_app_text: "Need more help? Contact us",
    update_language: "Update Language",
    items_and_quantity: "ITEMS AND QUANTITY",
    price: "PRICE",
    total: "Total",
    something_went_wrong: "Something went wrong",
    pull_down_to_refresh: "Pull down to refresh",
    failed_to_update_license: "Failed to update license",
    failed_to_upload_image: "Failed to upload image",
    please_select_an_expiry_date: "Please select an expiry date",
    please_enter_a_license_number: "Please enter a license number",
    please_upload_an_image: "Please upload an image",
    done: "Done",
    license_no: "License No",
    add_license_document: "Add License Document",
    expiry_date: "Expiry Date",
    license_image: "License Image",
    license_details_updated: "License Details Updated",
    license_document: "License Document",
    add_document: "Add Document",
    add: "Add",
    please_enter_a_plate_number: "Please enter a plate number",
    plate_no: "Plate No",
    add_registration_document: "Add Registration Document",
    driving_license: "Driving License",
    update: "Update",
    submitted_data: "Submitted Data",
    missing_data: "Missing Data",
    other_information: "Other information",
    password: "Password",
    phone: "Phone",
    available_amount: "Available Amount",
    enter_amount: "Enter Amount",
    confirm_withdraw: "Confirm Withdraw",
    successfully_created_the_withdraw_request: "Successfully created the withdraw request!",
    warning: "Warning",
    okay: "Okay",
    please_enter_a_valid_amount_you_have: "Please enter a valid amount. You have $",
    amount: "amount",
    the_withdraw_amount_must_be_atleast_10_or_greater: "The withdraw amount must be atleast 10 or greater.",
    please_enter_a_valid_number: "Please enter a valid number",
    current_balance: "Current Balance",
    withdraw_now: "Withdraw Now",
    pending_request: "Pending Request",
    recent_transactions: "Recent Transactions",
    requested: "Requested",
    transferred: "Transferred",
    cancelled: "Cancelled",
    pending: "Pending",
    paid: "Paid",
    your_request_for_withdrawal_has_been_submitted: "Your request for withdrawal has been submitted",
    usually_it_takes_1_2_business_days: "Usually it takes 1-2 business days",
    enter_your_credentials_to_login: "Enter Your Credentials to login",
    we_ll_check_if_you_have_an_account: "We'll check if you have an account",
    email: "Email",
    passowrd: "Password",
    forgot_password: "Forgot Password?",
    don_t_have_an_account_sign_up: "Don't have an account? Sign Up",
    enter_your_email_address_to_reset_your_password: "Enter your email address to reset your password",
    reset_password: "Reset Password",
    send_reset_password: "Send Reset Password",
    confirm_password: "Confirm Password",
    login: "Login",
    recent_activity: "Recent Activity",
    see_more: "See More",
    status: "Status",
    accepted: "ACCEPTED",
    picked: "PICKED",
    delivered: "DELIVERED",
    delivery_time: "DELIVERY TIME",
    no_orders_found: "NO ORDERS FOUND",
    order_details: "Order Details",
    store_name: "Store Name",
    pickup_order: "Pickup Order",
    delivery_order: "Delivery Order",
    order_time: "Order Time",
    total_items: "Total Items",
    total_price: "Total Price",
    payment_method: "Payment Method",
    order_amount: "Order Amount",
    not_paid_yet: "(Not paid yet)",
    order_comment: "Order Comment",
    no_comment: "No Comment",
    assign_me: "Assign me",
    icon_here: "Icon Here",
    well_done_rider: "Well Done Rider",
    order_number_key: "Order Number", 
    location_access: "Location access",
    location_permissions_are_required_to_use_this_app_kindly_open_settings_to_allow_location_access: "Location permissions are required to use this app. Kindly open settings to allow location access.",
    open_settings: "Open settings",
    continue_key: "Continue", 
    date_filter: "Date Filter",
    new_orders: "New Orders",
    processing: "Processing",
    delivered_key: "Delivered", 
    no_new_orders_yet: "No new orders yet!",
    vehicle_plate: "Vehicle Plate",
    language: "Language",
    you_don_t_have_any_orders_yet: "You don't have any orders yet!",
    no_delivered_orders_yet: "No delivered orders yet!",
    map_not_loaded: "Map not loaded.",
    please_check_for_permissions: "Please check for permissions.",
    pick_up: "Pick up",
    mark_as_delivered: "Mark as Delivered",
    vehicle_type_has_been_updated_successfully: "Vehicle Type has been updated successfully",
    help: "Help",
    about_us: "About Us",
    bank_management: "Bank Management",
    privacy_policy: "Privacy Policy",
    product_page: "Product Page",
    vehicle_type: "Vehicle Type",
    this_is_rider_s_location: "This is rider's location",
    restaurant: "Restaurant",
    delivery_address: "Delivery Address",
    order_marked_as: "Order marked as",
    enable_location_for_better_experience: "Enable Location For Better Experience",
    we_need_your_location_to_find_nearby_restaurants_ensure_accurate_delivery_and_provide_the_best_service_possible: "We need your location to find nearby restaurants, ensure accurate delivery, and provide the best service possible",
    logout: "Logout",
    mon: "MON",
    tue: "TUE",
    wed: "WED",
    thu: "THU",
    fri: "FRI",
    sat: "SAT",
    sun: "SUN",
    work_schedule_has_been_updated_successfully: "Work Schedule has been updated successfully.",
    start_time_must_be_earlier_than_end_time: "Start time must be earlier than end time.",
    end_time_must_be_greater_than_start_time: "End time must be greater than start time.",
    update_schedule: "Update Schedule",
    select_time_slot: "Select Time Slot",
    order_key: "ORDER", 
    addons: "Addons",
    options: "Options",
    special_instructions: "Special Instructions",
    sub_total: "Sub Total",
    tip: "Tip",
    delivery_charges: "Delivery Charges",
    comment: "Comment",
    decline: "Decline",
    accept: "Accept",
    time_left: "Time Left",
    hand_order_to_rider: "Hand Order to Rider",
    something_went_wrong_please_refresh: "Something went wrong Please refresh",
    bank_details: "Bank Details",
    other_details: "Other Details",
    address: "Address",
    delivery_orders: "Delivery Orders",
    pick_up_orders: "Pick up Orders",
    no_new_orders_yet_key: "No new orders yet!", 
    you_don_t_have_any_orders_yet_key: "You don't have any orders yet!", 
    no_delivered_key: "No delivered ", 
    type_your_message: "Type your message",
    theme: "Theme",
    dark: "Dark",
    light: "Light",
    you_have_an_existing_withdrawal_request: "You have an existing withdrawal request",
    please_wait_for_it_to_be_processed: "Please wait for it to be processed",
    you_are_currently_unavailable: "You are currently unavailable",
    your_wallet_is_currently_empty: "Your wallet is currently empty",
    orders: "Orders",
    set_preparation_time: "Set Preparation Time",
    tax: "Tax",
    wallet_amount: "Wallet Amount",
    delivered_orders: "Delivered Orders",
    processing_orders: "Processing Orders",
    order_detail: "Order Detail",
    chat: "Chat",
    work_schedule: "Work Schedule",
    contact_customer: "Contact Customer",
    no_new_chats: "No New Chats",
    please_select_a_start_date: "Please select a start date",
    please_select_an_end_date: "Please select an end date",
    start_date_cannot_be_after_end_date: "Start date cannot be after end date",
    please_log_in_to_view_your_earnings: "Please log in to view your earnings",
    total_earning: "Total Earning",
    store_id: "Store ID",
    unable_to_update_availability: "Unable to update availability",
    please_enter_a_valid_amount: "Please enter a valid amount",
    you_have: "You have",
    no_valid_slots_to_submit: "No valid slots to submit",
    time_slot_overlaps_with_another_existing_slot: "Time slot overlaps with another existing slot",
    has_overlapping_slots: "has overlapping slots",
    no_new_chats_yet: "No new chats yet!",
    no_delivered_orders_yet_key: "No delivered orders yet!",
    no_new_chats_yet_key: "No new chats yet!",
    deliver_order_to_customer: "Deliver Order to Customer",
    well_done_store: "Well Done Store",
    order_id_key: "Order ID",
    price_key: "PRICE",
    sub_total_key: "Sub Total",
    tip_key: "Tip",
    tax_key: "Tax",
    delivery_charges_key: "Delivery Charges",
    comment_key: "Comment",
  };