export const en = {
  selected_language: 'Selected Language',
  english: 'English',
  select_any_language_of_your_choice_to_change_the_content_of_the_app_to_your_required_language: 'Select any language of your choice to change the content of the app to your required language.',
  tasty: 'Tasty',
  breakfast: 'BreakFast',
  breakfast_is_everything_the_beginning_the_first_thing_it_is_the_mouthful_that_is_the_commitment_to_a_new_day_a_continuing_life: 'Breakfast is everything. The beginning, the first thing. It is the mouthful that is the commitment to a new day, a continuing life.',
  refreshing: 'Refreshing',
  drinks: 'Drinks',
  true_silence_is_the_rest_of_the_mind_and_is_to_the_spirit_what_sleep_is_to_the_body_nourishment_and_refreshment: 'True silence is the rest of the mind, and is to the spirit what sleep is to the body, nourishment and refreshment.',
  delicous: 'Delicous',
  icecream: 'Icecream',
  age_does_not_diminish_the_extreme_disappointment_of_having_a_scoop_of_ice_cream_fall_from_the_cone: 'Age does not diminish the extreme disappointment of having a scoop of ice cream fall from the cone',
  get_started: 'Get Started!',
  welcome_to_yalla_sometimes_all_you_need_is_love_but_a_little_food_now_and_then_doesn_t_hurt: "Welcome to Yalla, sometimes all you need is love. But a little food now and then doesn't hurt.",
  welcome_to_joylo: 'Welcome to Joylo',
  login: 'Login',
  register: 'Register',
  name: 'Name',
  phone: 'Phone',
  email: 'Email',
  email_or_phone: 'Email or Phone',
  password: 'Password',
  delivery_address: 'Delivery Address',
  your_full_delivery_address: 'Your full delivery address',
  required_details_e_g_floor_building: 'Required details -e.g. floor/ building',
  my_addresses: 'My Addresses',
  add_new_address: 'Add New Address',
  edit_address: 'Edit Address',
  or_register_with: 'Or Register With',
  forgot_password: 'Forgot Password?',
  or_login_with: 'Or Login With',
  turn_on_location_so_we_could_send_you_endless_taste_of_delicious_food: 'Turn on location so we could send you endless taste of delicious food.',
  turn_on_location: 'Turn on Location',
  permission_to_access_location_was_denied: 'Permission to access location was denied',
  permission_to_access_camera_roll_was_denied: 'Permission to access Camera Roll was denied',
  turn_on_location_and_try_again: 'Turn on location and try again',
  change_language: 'Change Language',
  menu: 'Menu',
  my_orders: 'My Orders',
  previous_order: 'Previous Order',
  notifications: 'Notifications',
  reviews: 'Reviews',
  profile: 'Profile',
  settings: 'Settings',
  help: 'Help',
  faqs: 'FAQs',
  chat: 'Chat',
  logout: 'Logout',
  your_cart: 'Your Cart',
  checkout: 'Checkout',
  payment: 'Payment',
  total_order_amount: 'Total Order Amount',
  select_items_to_reorder: 'Select items to Reorder',
  no_unread_notifications: 'No unread notifications',
  upload: 'Upload',
  save: 'Save',
  save_and_continue: 'SAVE AND CONTINUE',
  email_us_at: 'Email us at',
  where_do_we_find_the_food: 'Where do we find the food?',
  how_do_we_contact: 'How do we contact?',
  how_can_i_pay_the_delivery_person: 'How can I pay the delivery person?',
  is_the_service_available_in_my_city: 'Is the service available in my city?',
  you_can_find_the_food_at_your_nearest_store_without_paying_anything_to_customer_service_our_charges_are_extremely_low_as_compared_to_others: 'You can find the food at your nearest store without paying anything to customer service.Our charges are extremely low as compared to others.',
  you_can_contact_us_through_our_email_phone_number_or_our_website: 'You can contact us through our email, phone number or our website.',
  you_can_pay_the_delivery_person_in_person_or_pay_online_as_well_through_credit_or_debit_card: 'You can pay the delivery person in person or pay online as well through credit or debit card.',
  currently_this_service_is_available_in_cities_islamabad_and_karachi_you_can_contact_us_to_avail_this_service_in_your_city: 'Currently this service is available in cities Islamabad and Karachi you can contact us to avail this service in your city.',
  add: 'Add',
  quantity: 'Quantity',
  size: 'Size',
  add_to_cart: 'Add To Cart',
  order_now: 'Order Now',
  added_to_cart: 'Added to cart',
  no_items_in_cart: 'No items in cart',
  item_total: 'Item Total',
  delivery_charges: 'Delivery Charges',
  total: 'Total',
  contact_info: 'Contact Info',
  set_delivery_address: 'Set delivery address',
  set_payment_method_before_checkout: 'Set payment method before checkout',
  proceed_to_checkout: 'Proceed to Checkout',
  how_do_you_wish_to_pay: 'How do you wish to pay?',
  credit_debit_card: 'Credit/Debit Card',
  paypal: 'Paypal',
  cash: 'Cash',
  thank_you: 'Thank you!',
  your_order_is_confirmed: 'Your Order is confirmed',
  your_order_id: 'Your Order Id',
  your_order_amount: 'Your Order Amount',
  order_detail: 'Order Detail',
  payment_methods: 'Payment Methods',
  track_order: 'Track Order',
  back_to_menu: 'Back To Menu',
  food_item: 'Food item',
  delivered_to: 'Delivered to',
  write_a_review: 'Write a Review',
  order_received: 'Order Received',
  receive_special_offer: 'Received Special Offers',
  get_updates: 'Get Updates',
  your_order_is_on_its_way: 'Your order is on its way',
  turn_on_dark_theme: 'Turn on Dark Theme',
  delete_account: 'Delete Account',
  delivered: 'Delivered',
  completed: 'COMPLETED',
  cancelled: 'Cancelled',
  your_order_is_being_prepared: 'Your order is being prepared',
  rate_and_review: 'Rate and Review',
  more_detailed_reviews_get_more_visibility: 'More detailed reviews get more visibility...',
  submit: 'Submit',
  no_worries_let_us_help_you_out: 'No worries, let us help you out!',
  log_in_easily_by_entering_your_email: 'Log in easily by entering your email!',
  send: 'Send',
  apply: 'Apply',
  check_your_email_for_reset_password_link: 'Check your email for reset password link',
  please_select_your_required_language: 'Please select your required language',
  eng: 'eng',
  select_country_code: 'Select Country Code',
  this_payment_method_does_not_support_this_currency: 'This payment method does not support this Currency',
  login_create_account: 'Login/Create Account',
  no_reviews_yet: 'No Reviews Yet!',
  no_orders_yet: 'No Orders Yet!',
  error: 'Error',
  no_more_items_in_stock: 'No more items in stock',
  hungry: 'Hungry',
  back_to_food: 'Back to Food',
  let_s_find_some_favourites: "Let's find some favourites",
  subtotal: 'Subtotal',
  delivery_fee: 'Delivery Fee',
  do_you_have_a_voucher: 'Do you have a voucher ?',
  remove: 'Remove',
  change: 'Change',
  by_completing_this_order_i_agree_to_all_terms_conditions: 'By completing this order, I agree to all Terms & Conditions.',
  i_agree_and_i_demand_that_you_execute_the_ordered_service_before_the_end_of_the_revocation_period_i_am_aware_that_after_complete_fulfillment_of_the_service_i_lose_my_right_of_rescission: 'I agree and I demand that you execute the ordered service before the end of the revocation period. I am aware that after complete fulfillment of the service I lose my right of rescission.',
  coupon_discount_applied: 'Coupon discount applied',
  coupon_unavailable: 'Coupon Unavailable',
  invalid_coupon: 'Invalid Coupon',
  add_items_to_cart_before_checkout: 'Add items to cart before checkout',
  set_delivery_address_before_checkout: 'Set delivery address before checkout',
  favourites: 'Favourites',
  favourite_restaurants: 'Favourite Restaurants',
  no_favourites_saved: 'No Favourites Saved',
  you_ll_see_all_your_favourites_here_to_make_ordering_even_faster: "You'll see all your favourites here, to make ordering even faster.",
  just_look_for_the: 'Just look for the',
  tax_charges: 'Tax Charges',
  view_your_cart: 'VIEW YOUR CART',
  featured: 'Featured',
  all_restaurants: 'All Restaurants',
  delivery_details: 'Delivery Details',
  pickup_details: 'Pickup Details',
  tip: 'Tip',
  review_regarding_your_order: 'Review regarding your order?',
  any_suggestion: 'Any suggestion?',
  new_user_create_an_account: 'New User? Create an account',
  signup_or_login: 'Signup or login',
  or: 'or',
  by_continue_you_agree_to_our: 'By continue, you agree to our',
  term_conditions: 'Term & Conditions',
  privacy_policy: 'Privacy Policy',
  and: 'and',
  what_s_your_email: "What's your Email?",
  we_ll_check_if_you_ve_an_account: "We'll check if you've an account",
  sign_in_with_your_email: 'Sign in with your email',
  continue: 'Continue',
  email_is_required: 'Email is required',
  invalid_email: 'Invalid Email!',
  password_is_required: 'Password is required',
  invalid_password_password_must_be_at_least_8_characters_long_and_contain_at_least_one_letter_and_one_number: 'Invalid Password. Password must be at least 8 characters long and contain at least one letter and one number.',
  let_s_get_you_started: "Let's get you started!",
  first_lets_create_your_account: 'First, lets create your account',
  firstname_is_required: 'Firstname is required!',
  invalid_first_name: 'Invalid First Name!',
  lastname_is_required: 'Lastname is required!',
  invalid_last_name: 'Invalid Last Name!',
  phone_number_is_required: 'Phone number is required!',
  invalid_phone_number: 'Invalid Phone number',
  verify_your_email: 'Verify Your Email',
  enter_otp_to_verify_your_email_securely_your_privacy_is_paramount_your_data_remains_protected: 'Enter OTP to verify your Email securely. Your privacy is paramount; your data remains protected.',
  verify_your_phone_number: 'Verify Your Phone Number',
  please_enter_otp_we_sent_to_your_phone_number: 'Please enter OTP we sent to your phone number.',
  wrong_otp_please_try_again: 'Wrong otp. Please try again!',
  resend: 'Resend',
  enter_your_email_and_we_ll_send_you_an_otp_to_reset_your_password: "Enter your email and we'll send you an OTP to reset your password.",
  back_to_login: 'Back to login',
  set_your_password: 'Set your Password',
  kindly_enter_your_password: 'Kindly enter your password',
  confirm_password_is_required: 'Confirm password is required!',
  enter_phone_number: 'Enter Phone Number',
  we_ll_use_your_number_only_if_we_need_to_contact_you_about_your_order_next_we_ll_text_you_a_code_to_make_sure_we_got_the_right_number: "We'll use your number only if we need to contact you about your order.Next we'll text you a code to make sure we got the right number.",
  home: 'Home',
  work: 'Work',
  other: 'Other',
  appartment: 'Appartment',
  house: 'House',
  office: 'Office',
  add_label: 'Add Label',
  personal_details: 'Personal details',
  update: 'Update',
  mobile: 'Mobile',
  add_phone: 'Add Phone',
  verified: 'Verified',
  verify: 'verify',
  unverified: 'Unverified',
  change_password: 'Change password',
  current_password: 'Current password',
  new_password: 'New Password',
  password_updated: 'Password Updated',
  search_address: 'Search Address',
  loading: 'Loading...',
  pending: 'PENDING',
  accepted: 'Accepted',
  assigned: 'Assigned',
  picked: 'Picked',
  order_received_we_are_now_waiting_for_the_store_to_accept_your_order_you_will_be_notified_as_soon_as_it_s_confirmed: "Order received! We are now waiting for the store to accept your order. You will be notified as soon as it's confirmed.",
  preparing_your_food_will_be_delivered_very_soon: 'Preparing your food. Will be delivered very soon.',
  your_rider_has_picked_up_the_order_get_ready_for_some_delicious_food: 'Your rider has picked up the order. Get ready for some delicious food!',
  order_is_delivered: 'Order is delivered.',
  order_is_completed: 'Order is completed.',
  your_order_is_cancelled_if_you_have_any_questions_please_reach_out_to_our_support_team: 'Your order is cancelled. If you have any questions, please reach out to our support team.',
  waiting_for_restaurant_to_accept: 'Waiting for restaurant to accept',
  food_is_being_prepared: 'Food is being prepared',
  assigned_a_rider: 'Assigned a rider',
  rider_on_his_way: 'Rider on his way',
  we_re_sorry_your_order_was_cancelled: "We're sorry, Your order was cancelled.",
  your_order_at: 'Your order at',
  delivery: 'Delivery',
  minutes: 'minutes',
  min: 'Min',
  closed: 'Closed',
  we_are_now_waiting_for_the_store_to_accept_your_order: 'We are now waiting for the store to accept your order.',
  the_restaurant_rider_will_be_at_your_place_around: 'The restaurant rider will be at your place around.',
  your_order_from: 'Your order from:',
  order_number: 'Order Number:',
  active_orders: 'Active Orders',
  past_orders: 'Past Orders',
  continue_with_google: 'Continue with Google',
  continue_with_email: 'Continue with Email',
  cancel: 'Cancel',
  delete_my_account: 'Delete my Account',
  are_you_sure_you_want_to_delete_account: 'Are you Sure you want to delete Account?',
  let_s_chat_with_rider: "Let's Chat with rider",
  your_order_is: 'Your order is',
  no_items_exists: 'No items exists',
  pickup_address: 'PickUp Address',
  selected_location: 'Selected Location',
  there_are_no_reviews_yett: 'There are no reviews yett.',
  opening_times: 'Opening times',
  closed_all_day: 'Closed all day',
  about: 'About',
  it_s_empty_here: "It's empty here",
  you_haven_t_saved_any_address_yet: "You haven't saved any address yet.",
  click_add_new_address_to_get_started: 'Click Add New Address to get started',
  change_address: 'Change Address',
  pick_up: 'Pick-up',
  custom: 'Custom',
  select_pickup_date_and_time: 'Select Pickup date and time',
  select_delivery_date_and_time: 'Select Delivery date and time',
  view_less: 'View Less',
  view_all: 'View All',
  current_location: 'Current Location',
  use_my_current_location: 'Use my current Location',
  tap_on_this_message_to_open_settings_then_allow_app_to_use_location_from_permissions: 'Tap on this message to open Settings then allow app to use location from permissions.',
  to_find_restaurants_near_you_we_just_need_your_location: 'To find restaurants near you, we just need your location',
  set_location_manually: 'Set Location Manually',
  set_location: 'Set Location',
  cart_is_empty: 'Cart is empty',
  favourite_list_updated: 'Favourite list updated',
  the_minimum_amount_of: 'The minimum amount of ',
  for_your_order_has_not_been_reached: ' for your order has not been reached.',
  set_payment_method_before_checkout: 'Set payment method before checkout',
  phone_number_is_not_verified_kindly_verify_phone_number: 'Phone number is not verified. Kindly verify phone number.',
  phone_number_has_been_verified_successfully: 'Phone number has been verified successfully!.',
  phone_number_has_been_added_successfully: 'Phone number has been added successfully!.',
  one_or_more_item_is_not_available: 'One or more item is not available',
  account_deactivated: 'Account Deactivated',
  address_updated: 'Address Updated',
  an_error_occured_please_try_again: 'An error occured. Please try again ',
  otp_for_reset_password_has_been_sent_to_your_email: 'OTP for reset password has been sent to your email.',
  password_reset_successfully: 'Password Reset successfully!',
  password_must_match_with_confirm_password: 'Password must match with confirm password',
  your_email_is_associated_with: 'Your email is associated with ',
  kindly_continue_with: '. Kindly continue with ',
  error_while_checking_email_try_again_later: 'Error while checking email. Try again later!',
  error_in_login_error: 'Error in login Error',
  error_while_logging_in_please_try_again_later: 'Error while logging in. Please try again later',
  your_account_has_been_created: 'Your account has been created.',
  invalid_password: 'Invalid password',
  user_s_info_updated: "User's Info Updated",
  name_is_required: 'Name is required',
  notification_status_updated: 'Notification Status Updated',
  notification_do_not_work_on_simulator: 'Notification do not work on simulator',
  error_in_profile: 'Error in profile',
  invalid_amount: 'Invalid Amount',
  amount_must_be_greater_than_0: 'Amount must be greater than 0',
  other_amount: 'Other amount',
  add_other_amount: 'Add Other amount',
  otp_resent_to_your_email: 'OTP resent to your email.',
  search: 'Search',
  search_for_restaurants: 'Search for restaurants',
  search_for_items: 'Search for items',
  message: 'Message',
  apt_floor: 'Apt | Floor',
  confirm_password: 'Confirm Password',
  special_instructions: 'Special instructions',
  any_specific_preferences: 'Any specific preferences?',
  optional: 'Optional',
  e_g_no_mayo: 'E .g No mayo',
  mobile_number: 'Mobile Number',
  first_name: 'First name',
  last_name: 'Last name',
  customize: 'Customize',
  my_vouchers: 'My Vouchers',
  product_page: 'Product Page',
  docs: 'Docs',
  blog: 'Blog',
  about_us: 'About Us',
  paypal_checkout: 'Paypal Checkout',
  stripe_checkout: 'Stripe Checkout',
  tipping: 'Tipping',
  order_palced: 'Order palced',
  select_location: ' Select Location',
  language_setting: 'Language Setting',
  i_want_to_receive_special_offers_and_promotions_from_us_via_email: 'I want to receive special offers and promotions from us via email',
  i_want_to_receive_special_offers_and_promotions_from_us_via_notifications: 'I want to receive special offers and promotions from us via notifications',
  turn_on_dark_theme: 'Turn on Dark Theme',
  select_language: 'Select Language',
  select: 'Select',
  delete_account: 'DELETE ACCOUNT',
  eta: 'ETA',
  contact_your_rider: 'Contact your Rider',
  select_country: 'Select Country',
  mon: 'MON',
  tue: 'TUE',
  wed: 'WED',
  thu: 'THU',
  fri: 'FRI',
  sat: 'SAT',
  sun: 'SUN',
  delivery_address_is_required: 'Delivery address is required',
  select_variation: 'Select Variation',
  select_one: 'Select one',
  required: 'Required',
  how_was_your_meal: 'How was your meal?',
  was_it_nice_or_bad_lets_talk_about_it: 'Was it nice or bad,Lets talk about it',
  rate_your_order: 'Rate Your Order',
  tell_about_your_experience: 'Tell about your Experience',
  select_items: 'Select Items',
  you_don_t_have_any_past_order_yet_try_one_of_our_awesome_restaurants_and_place_your_first_order: "You don't have any past order yet. Try one of our awesome restaurants and place your first order!",
  browse_restaurants_in_your_area: 'Browse RESTAURANTS IN YOUR AREA',
  rate_order: 'Rate Order',
  enter_your_voucher_code: 'Enter your voucher code',
  something_went_wrong_check_your_network_and_try_again: 'Something went wrong. Check your network and try again.',
  no_restaurants: 'No Restaurants',
  by_leaving_this_restaurant_page_the_items_you_ve_added_to_cart_will_be_cleared: 'By leaving this restaurant page, the items you`ve added to cart will be cleared ',
  ok: 'OK',
  order: 'Order',
  items_and_quantity: 'ITEMS AND QUANTITY',
  price: 'PRICE',
  edit: 'Edit',
  my_account: 'My Account',
  estimated_delivery_time: 'Estimated delivery time',
  current: 'Current',
  past: 'Past',
  delivered_on: 'delivered on',
  address: 'Address',
  language: 'Language',
  save_address: 'Save Address',
  apartment: 'Apartment',
  tap_to_rate: 'Tap to Rate',
  location_type: 'Location Type',
  the_location_type_helps_us_to_find_you_better: 'The location type helps us to find you better',
  additional_items: 'Additional Items',
  we_are_not_currently_available_in_your_area: 'We are not currently available in your area',
  no_restaurant_currently_offers_delivery_in_your_area: 'No restaurant currently offers delivery in your area',
  filters: 'Filters',
  frequently_bought_together: 'Frequently Bought Together',
  details: 'Details',
  most_ordered_right_now: 'Most ordered right now',
  order_it_again: 'Order it again',
  top_brands: 'Top Brands',
  top_picks_for_you: 'Top Picks for you',
  your_order_is_cancelled: 'Your order is cancelled',
  if_you_have_any_questions_feel_free_to_reach_out_to_our_support_team: 'If you have any questions feel free to reach out to our support team',
  cancel_your_order: 'Cancel your order',
  we_ve_got_your_order_and_may_find_you_a_rider_any_second_now_cancel_anyway: "We've got your order and may find you a rider any second now. Cancel anyway",
  i_will_wait_for_my_order: 'I will wait for my order',
  explore_cities: 'Explore Cities',
  service_fee_applies: 'Service Fee applies',
  see_reviews: 'See Reviews',
  days_ago: 'Days ago',
  location: 'Location',
  you_have_not_saved_any_address_yet: 'You have not saved any address yet',
  vat_already_included: 'VAT already included',
  send_a_reply_to_rider: 'Send a reply to rider!',
  within: 'Within',
  add_a_tip_for_rider: 'Add a Tip for Rider',
  voucher: 'Voucher',
  payment_summary: 'Payment Summary',
  voucher_discount: 'Voucher Discount',
  add_voucher_code: 'Add Voucher Code',
  sign_up_to_get_your_discount: 'Sign up to get your discount',
  food_delivery: 'Food Delivery',
  order_food_you_love: 'Order food you love',
  grocery: 'Grocery',
  essentials_delivered_fast: 'Essentials delivered fast',
  enter_your_email_and_password: 'Enter Your Email and Password',
  your_email_already_exists: 'Your email already exists',
  retry_after: 'Retry after',
  enter_otp_to_verify_your_phone_number_securely_your_privacy_is_paramount_your_data_remains_protected: 'Enter OTP to verify your phone number securely. Your privacy is paramount; your data remains protected.',
  create_account: 'Create Account',
  select_items_to_order_again: 'Select Items to order again',
  rating_reviews: 'Rating & Reviews',
  all_ratings: 'All Ratings',
  browse_all_cities: 'Browse All Cities',
  minimum: 'Minimum',
  how_do_i_place_an_order: 'How do I place an order? ',
  to_place_an_order_simply_browse_through_our_menu_select_the_items_you_d_like_to_order_and_proceed_to_checkout_you_can_choose_your_preferred_payment_method_and_delivery_address_before_confirming_your_order: "To place an order, simply browse through our menu, select the items you'd like to order, and proceed to checkout. You can choose your preferred payment method and delivery address before confirming your order.",
  what_are_the_delivery_charges: 'What are the delivery charges?',
  delivery_charges_vary_depending_on_your_location_and_the_restaurant_you_re_ordering_from_you_can_view_the_delivery_charges_applicable_to_your_order_before_finalizing_it_during_the_checkout_process: "Delivery charges vary depending on your location and the restaurant you're ordering from. You can view the delivery charges applicable to your order before finalizing it during the checkout process.",
  can_i_track_my_order: 'Can I track my order?',
  yes_you_can_track_your_order_in_real_time_from_the_moment_it_s_confirmed_to_when_it_s_out_for_delivery_you_ll_receive_updates_on_the_status_of_your_order_through_notifications_on_the_app: "Yes, you can track your order in real-time from the moment it's confirmed to when it's out for delivery. You'll receive updates on the status of your order through notifications on the app.",
  how_long_does_delivery_take: 'How long does delivery take?',
  delivery_times_may_vary_depending_on_factors_such_as_the_restaurant_s_preparation_time_traffic_conditions_and_your_location_however_we_strive_to_deliver_your_order_within_a_reasonable_timeframe_typically_ranging_from_30_to_60_minutes: "Delivery times may vary depending on factors such as the restaurant's preparation time, traffic conditions, and your location. However, we strive to deliver your order within a reasonable timeframe, typically ranging from 30 to 60 minutes.",
  can_i_cancel_my_order_after_it_s_been_placed: "Can I cancel my order after it's been placed?",
  yes_you_can_cancel_your_order_once_it_is_placed_however_once_the_order_has_been_prepared_and_sent_out_for_delivery_you_can_no_longer_cancel_the_order_you_may_contact_the_restaurant_directly_for_assistance: 'Yes you can cancel your order once it is placed. However, once the order has been prepared and sent out for delivery, you can no longer cancel the order. You may contact the restaurant directly for assistance.',
  how_can_i_provide_feedback_on_my_experience: 'How can I provide feedback on my experience?',
  you_can_provide_feedback_through_the_app_by_rating_your_order_and_leaving_comments_you_can_also_give_a_rating_to_the_restaurant_and_leave_a_review: 'You can provide feedback through the app by rating your order and leaving comments. You can also give a rating to the restaurant and leave a review.',
  can_i_order_from_multiple_places_at_the_same_time: 'Can I order from multiple places at the same time?',
  unfortunately_you_can_t_choose_from_multiple_restaurants_within_the_same_order_however_you_can_place_separate_orders_from_different_restaurants_at_the_same_time: "Unfortunately, you can't choose from multiple restaurants within the same order.However, you can place separate orders from different restaurants at the same time.",
  away: 'away',
  place_order: 'Place Order',
  continue_as_guest: 'Continue as Guest',
  restaurant_closed_at_the_moment: 'Restaurant Closed at the moment',
  go_back_to_restaurants: 'Go back to restaurants',
  see_menu: 'See Menu',
  ask_for_contactless_delivery: 'Ask for contactless delivery',
  no_active_orders_yet: 'No Active Orders Yet!',
  you_ll_see_your_active_orders_here: "You'll see your active orders here.",
  let_s_order_something: "Let's order something!",
  no_past_orders_yet: 'No Past Orders Yet!',
  you_ll_see_your_past_orders_here: "You'll see your past orders here.",
  all_grocery_shops: 'All Grocery Shops',
  search_for_grocery_shops: 'Search for grocery shops',
  no_grocery_shop_currently_offers_delivery_in_your_area: 'No grocery shop currently offers delivery in your area',
  restaurant_name: 'Restaurant Name',
  location_type_not_selected: 'Location type not selected',
  sort: 'Sort',
  offers: 'Offers',
  rating: 'Rating',
  cuisines: 'Cuisines',
  distance: 'Distance',
  fast_delivery: 'Fast Delivery',
  relevance: 'Relevance',
  free_delivery: 'Free Delivery',
  accept_vouchers: 'Accept Vouchers',
  deal: 'Deal',
  '3_rating': '3+ Rating',
  '4_rating': '4+ Rating',
  '5_star_rating': '5 star Rating',
  newest: 'Newest',
  highest_rating: 'Highest Rating',
  lowest_rating: 'Lowest Rating',
  cart_addresses: 'Cart Addresses',
  address_deleted: 'Address deleted!',
  successfully_logged_out: 'Successfully logged out',
  something_went_wrong: 'Something went wrong',
  check_your_internet_connection: 'Check your internet connection',
  select_city: 'Select City',
  provided_phone_number_already_exist: 'Provided phone number already exist!',
  error_while_checking_phone_number_try_again_later: 'Error while checking phone number. Try again later!',
  would_you_like_to_add_these: 'Would you like to add these?',
  how_was_your_order: 'How was your order?',
  tell_others_about_your_experience_with: 'Tell others about your experience with',
  type_here: 'Type Here',
  review: 'Review',
  logging_out: 'Logging out?',
  see_you_again_soon: 'See you again soon!',
  enter_code: 'ENTER CODE',
  enter_amount: 'ENTER AMOUNT',
  apply_a_voucher: 'Apply a Voucher',
  input_code: 'Input Code',
  add_tip: 'Add Tip',
  are_you_sure_you_want_to_delete_your_account_this_action_cannot_be_undone_deleting_your_account_will_permanently_remove_all_of_your_data_including_your_orders_and_preferences_if_you_proceed_you_will_lose_access_to_your_account_and_its_benefits: 'Are you sure you want to delete your account? This action cannot be undone. Deleting your account will permanently remove all of your data, including your orders and preferences. If you proceed, you will lose access to your account and its benefits.',
  yes_i_m_sure: "Yes, I'm Sure",
  no_don_t_delete_it: "No, Don't Delete it",
  delivery_time: 'Delivery Time',
  pickup_time: 'Pickup Time',
  asap: 'ASAP',
  login_sign_up: 'Login/Sign Up',
  sales_tax: 'Sales Tax',
  minimum_order: 'Minimum Order',
  please_select_an_option_for_addon: 'Please select an option for addon',
  need_more_help_contact_us: 'Need more help? Contact us',
  hi: 'Hi',
  your_favourites: 'Your Favourites',
  see_all: 'See All',
  quick_links: 'Quick links',
  order_again: 'Order Again',
  customer_support: 'Customer support',
  order_history: 'Order history',
  account: 'Account',
  map: 'Map',
  opening_hours: 'Opening hours',
  delivery_information: 'Delivery information',
  contact: 'Contact',
  view_website: 'View website',
  website: 'Website',
  restaurant: 'Restaurant',
  delivery_cost: 'Delivery cost',
  if_you_have_allergies_or_other_dietary_restrictions_please_contact_the_restaurant_the_restaurant_will_provide_food_specific_information_upon_request: 'If you have allergies or other dietary restrictions, please contact the restaurant. The restaurant will provide food-specific information upon request.',
  preservation_of_the_authentic_taste_of_all_traditional_foods_is_upheld_here: 'Preservation of the authentic taste of all traditional foods is upheld here.',
  none: 'none',
  please_enter_your_passwords_now_for_access: 'Please enter your passwords now for access!',
  joylo: 'Joylo',
  enjoy_the_best_restaurants_or_get_what_you_need_from_nearby_stores_delivered: 'Enjoy the best restaurants or get what you need from nearby stores, delivered',
  phone_number: 'Phone Number',
  send_text_with_code: 'Send text with code',
  resend_otp: 'Resend OTP',
  get_registered: 'Get Registered',
  legal: 'Legal',
  terms_of_service: 'Terms of Service',
  no_results_found: 'No Results Found',
  recent_searches: 'Recent Searches',
  clear: 'Clear',
  saved_addresses: 'Saved Addresses',
  delete: 'Delete',
  are_you_sure_you_want_to_delete_selected_addresses: 'Are you sure you want to delete selected addresses?',
  not_verifid: 'Not Verifid',
  browse_categories: 'Browse Categories',
  popular_right_now: 'Popular right now',
  i_feel_like_eating: 'I feel like eating...',
  restaurants_near_you: 'Restaurants near you',
  fresh_finds_await: 'Fresh finds await...',
  grocery_list: 'Grocery List',
  top_grocery_picks: 'Top grocery picks',
  top_grocery_brands: 'Top Grocery Brands',
  top_restaurant_brands: 'Top Restaurant Brands',
  our_brands: 'Our brands',
  restaurants: 'Restaurants',
  stores: 'Stores',
  lets_shop_for: 'Lets shop for',
  collections: 'Collections',
  all_stores: 'All Stores',
  top_picks: 'Top Picks',
  all_grocery: 'All Grocery',
  all_restaurant: 'All Restaurant',
  from_your_previous_orders: 'From your previous orders',
  top_picked_restaurants_for_you: 'Top picked restaurants for you',
  top_brands_in_your_area: 'Top brands in your area',
  most_ordered_grocery_stores: 'Most ordered grocery stores',
  most_ordered_restaurants: 'Most ordered restaurants',
  discovery: 'Discovery',
  store: 'Store',
  login_required: 'Login Required',
  payment_not_successfull: 'Payment Not Successfull',
  this_payment_method_does_not_support_this_currency: 'This payment method does not support this Currency',
  open: 'Open',
  pickup: 'Pickup',
  add_a_message_for_the_restaurant: 'Add a message for the restaurant',
  special_requests_allergies_dietary_restriction: 'Special requests, allergies, dietary restriction',
  kindly_be_advised_that_your_message_could_also_be_visible_to_the_courier_partner_responsible_for_delivering_your_order_to_the_venue: 'Kindly be advised that your message could also be visible to the courier partner responsible for delivering your order to the venue.',
  explore_joylo_cities: 'Explore Joylo Cities',
  card: 'Card',
  the_label_selectedlabel_already_exists_please_choose_a_different_one: "The label '{{selectedLabel}}' already exists. Please choose a different one.",
  update_available: 'Update Available',
  a_new_version_of_the_app_is_available_please_update_to_continue_using_the_app: 'A new version of the app is available. Please update to continue using the app.',
  update_now: 'Update Now',
  close: 'Close',
  instruction_for_the_courier: 'Instruction for the courier',
  instructions: 'Instructions',
  popular: 'Popular',
  reloading: 'Reloading...',
  new_orders: 'New Orders',
  sorry_we_can_t_deliver_to_your_address: "Sorry! we can't deliver to your address.",
  your_order_amount_is_below_the_restaurant_s_minimum_order_requirement_please_add_more_items_to_your_cart: "Your order amount is below the restaurant's minimum order requirement. Please add more items to your cart.",
  can_t_delivery_to_this_address: "Can't delivery to this address",
  currently_restaurant_is_not_delivering_to_your_selected_address: 'Currently Restaurant is not delivering to your selected address',
  select_another_one: 'Select another one',
  no_matching_results: 'No matching results',
  try_adjusting_your_filters_or_explore_other_options_to_find_what_you_re_looking_for: "Try adjusting your filters or explore other options to find what you're looking for.",
  applied_filters: 'Applied Filters',
  whatsapp_is_not_installed_on_the_device: 'WhatsApp is not installed on the device',
  install_it: 'Install it',
  are_you_sure_you_want_to_delete_selected_addresses: 'Are you sure you want to delete selected addresses?',
  phone_number_not_verified: 'Phone number is not verified. Kindly verify phone number.',
  delete_confirmation: 'Delete Confirmation',
  delete_account: 'Delete Account',
  could_not_delete_account_please_try_again_later: "Couldn't delete account. Please try again later",
  use_current_location: 'Use Current Location',
  browse_cities: 'Browse Cities',
  add_address: 'Add Address',
  save_btn: 'Save',
  not_available_in_your_area: 'Not Available in Your Area',
  no_matching_results_desc: 'Try adjusting your filters or explore other options to find what you\'re looking for.',
  no_restaurant: 'No Restaurant',
  no_grocery: 'No Grocery',
  faq1: 'How do I place an order? ',
  faq1Description:
    "To place an order, simply browse through our menu, select the items you'd like to order, and proceed to checkout. You can choose your preferred payment method and delivery address before confirming your order.",
  faq2: 'What are the delivery charges?',
  faq2Description:
    "Delivery charges vary depending on your location and the restaurant you're ordering from. You can view the delivery charges applicable to your order before finalizing it during the checkout process.",
  faq3: 'Can I track my order?',
  faq3Description:
    "Yes, you can track your order in real-time from the moment it's confirmed to when it's out for delivery. You'll receive updates on the status of your order through notifications on the app.",
  faq4: 'How long does delivery take?',
  faq4Description:
    "Delivery times may vary depending on factors such as the restaurant's preparation time, traffic conditions, and your location. However, we strive to deliver your order within a reasonable timeframe, typically ranging from 30 to 60 minutes.",
  faq5: "Can I cancel my order after it's been placed?",
  faq5Description:
    'Yes you can cancel your order once it is placed. However, once the order has been prepared and sent out for delivery, you can no longer cancel the order. You may contact the restaurant directly for assistance.',
  faq6: 'How can I provide feedback on my experience?',
  faq6Description:
    'You can provide feedback through the app by rating your order and leaving comments. You can also give a rating to the restaurant and leave a review.',
  faq7: 'Can I order from multiple places at the same time?',
  faq7Description:
    'Unfortunately, you can’t choose from multiple restaurants within the same order. However, you can place separate orders from different restaurants at the same time.',
  search_items: "Search Items",
}
